import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Traxora AI",
  description: "Terms governing your use of the Traxora AI platform.",
};

const LAST_UPDATED = "June 8, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="text-lg font-bold text-[#F1F5F9] mb-3">{title}</h2>
      <div className="text-sm text-[#7B8DB4] leading-relaxed space-y-3">{children}</div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen text-[#F1F5F9] px-6 py-16">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="flex items-center gap-2 text-sm text-[#4B5675] hover:text-[#7B8DB4] transition-colors mb-12 w-fit">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="15 18 9 12 15 6" />
          </svg>
          Back to home
        </Link>

        <div className="mb-10">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-9 h-9 rounded-xl bg-emerald-600 flex items-center justify-center">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
                <polyline points="16 7 22 7 22 13" />
              </svg>
            </div>
            <span className="font-bold text-[#F1F5F9]">Traxora AI</span>
          </div>
          <h1 className="text-4xl font-black mb-3">Terms of Service</h1>
          <p className="text-sm text-[#4B5675]">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl px-5 py-4 mb-10">
          <p className="text-sm font-bold text-amber-300 mb-1">Not Financial Advice</p>
          <p className="text-xs text-amber-400 leading-relaxed">Traxora AI provides market analysis tools for educational and informational purposes only. Nothing on this platform constitutes financial advice, investment advice, or a recommendation to buy or sell any security. Past signal performance does not guarantee future results. Always consult a licensed financial advisor before making investment decisions.</p>
        </div>

        <Section title="1. Acceptance">
          <p>By accessing or using Traxora AI, you agree to these Terms of Service. If you do not agree, do not use the platform.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>Traxora AI is a market analysis research tool that uses AI to generate signals, scanning results, and journal analyses. All outputs are for educational purposes. We make no guarantee of accuracy, completeness, or fitness for a particular purpose.</p>
        </Section>

        <Section title="3. No Financial Advice">
          <p>All signals, recommendations, analysis, and commentary generated by Traxora AI are for informational and educational purposes only. They do not constitute:</p>
          <ul className="list-disc list-inside space-y-1 text-[#4B5675]">
            <li>Financial or investment advice</li>
            <li>A solicitation to buy or sell any security</li>
            <li>A guarantee of any particular outcome or return</li>
          </ul>
          <p>You are solely responsible for your trading decisions. Traxora AI and its operators are not liable for any losses incurred.</p>
        </Section>

        <Section title="4. Accounts and Access">
          <p>Traxora AI is free to use and does not require an account. Your watchlist, journal and portfolio are tied to an anonymous identifier stored in your browser. We reserve the right to limit or suspend access for abuse or violations of these terms.</p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to: scrape or automate access to the platform; reverse-engineer our AI models or algorithms; share account credentials; use the service in any jurisdiction where doing so is illegal; or use the service to manipulate markets.</p>
        </Section>

        <Section title="6. Subscriptions and Billing">
          <p>Pro subscriptions are billed monthly at the stated price. You may cancel at any time from the Settings page. Access continues until the end of the current billing period. Refunds are handled at our discretion for billing errors.</p>
          <p>Prices may change with 30 days&apos; notice. Continued use after a price change constitutes acceptance of the new price.</p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>All content, signals, analysis, UI, and code produced by Traxora AI are our intellectual property. You may not reproduce, distribute, or create derivative works without express written permission.</p>
        </Section>

        <Section title="8. Disclaimers and Limitation of Liability">
          <p>The service is provided &ldquo;as is&rdquo; without any warranty of any kind. To the maximum extent permitted by law, Traxora AI and its operators are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform, including trading losses.</p>
        </Section>

        <Section title="9. Changes to Terms">
          <p>We may update these terms. We&apos;ll notify you of material changes via email. Continued use after changes constitutes acceptance.</p>
        </Section>

        <Section title="10. Governing Law">
          <p>These terms are governed by the laws of the United States. Disputes will be resolved in the courts of the applicable jurisdiction.</p>
        </Section>

        <Section title="11. Contact">
          <p>Questions? Email <a href="mailto:thecompetitormindset@gmail.com" className="text-emerald-400 hover:text-emerald-300 underline">thecompetitormindset@gmail.com</a>.</p>
        </Section>

        <div className="border-t border-[#252345] pt-8 flex gap-6 text-xs text-[#4B5675]">
          <Link href="/privacy" className="hover:text-[#7B8DB4] transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-[#7B8DB4] transition-colors">Back to Traxora AI</Link>
        </div>
      </div>
    </div>
  );
}
