"""Generate app/typescale.css: snaps every text size used in the app to one scale.

Run after adding new text-[Npx] sizes:  python3 scripts/gen-typescale.py
"""
import re
import subprocess

sizes = sorted({float(x) for x in re.findall(
    r"text-\[([0-9.]+)px\]",
    subprocess.run(["grep", "-rhoE", r"text-\[[0-9.]+px\]", "app"], capture_output=True, text=True).stdout,
)})


def snap(px: float) -> int:
    if px <= 12.5: return 12
    if px <= 15.5: return 14
    if px <= 18: return 16
    if px <= 26: return 20
    if px <= 36: return 28
    return 40


NAMED = {"xs": 12, "sm": 14, "base": 16, "lg": 16, "xl": 20, "2xl": 28, "3xl": 28, "4xl": 40, "5xl": 40, "6xl": 40}
BREAKPOINTS = {"": None, "sm:": 640, "md:": 768, "lg:": 1024, "xl:": 1280}


SCOPE = "html body:not(:has(.lp-root))"  # every page except the landing page


def esc(s: str) -> str:
    return s.replace(".", r"\.").replace("[", r"\[").replace("]", r"\]").replace(":", r"\:")


def weight(size: int) -> str:
    # Big numbers and titles are medium, never heavy — the same look as the
    # Overview headline. Everything else keeps its own (capped) weight.
    return "font-weight:500!important;" if size >= 28 else ""


def rules(prefix: str) -> list[str]:
    out = [f"{SCOPE} .{esc(f'{prefix}text-[{px:g}px]')}{{font-size:{snap(px)}px!important;{weight(snap(px))}}}" for px in sizes]
    out += [f"{SCOPE} .{esc(f'{prefix}text-{k}')}{{font-size:{v}px!important;{weight(v)}}}" for k, v in NAMED.items()]
    return out


css = [
    "/* ── Type scale (generated by scripts/gen-typescale.py — don't edit by hand) ──",
    "   Every page except the landing page. Every size snaps to six steps — 12 caption,",
    "   14 body, 16 subheading, 20 section, 28 page title / big number, 40 hero —",
    "   and responsive variants keep their breakpoints. Weights: 400/500. */",
]
for prefix, width in BREAKPOINTS.items():
    r = rules(prefix)
    css += r if width is None else [f"@media (min-width:{width}px){{", *("  " + x for x in r), "}"]
S = SCOPE
small = ",".join(f".{esc(f'text-[{px:g}px]')}" for px in sizes if snap(px) == 12) + ",.text-xs"
css += [
    # Small text (badges, chips, little buttons) is medium at most — bold at 12px looks heavier than everything around it.
    S + f" :is({small}):is(.font-bold,.font-black,.font-extrabold,.font-semibold) {{ font-weight: 500 !important; }}",
    # Ordinary digits everywhere, so numbers look the same in boxes as in text.
    S + " :is(.font-mono,[data-price],.tabular-nums,.fn-num) { font-variant-numeric: normal !important; font-feature-settings: normal !important; }",
    S + ' main :is([style*="font-weight: 450"],[style*="font-weight:450"]) { font-weight: 500 !important; }',
    S + ' main :is([style*="font-weight: 650"],[style*="font-weight: 700"],[style*="font-weight: 800"],[style*="font-weight: 900"]) { font-weight: 500 !important; }',
    S + ' :is(b, strong, th, h1, h2, h3, h4, h5, h6) { font-weight: 500; }',
    S + ' svg text:is([font-weight="700"],[font-weight="800"],[font-weight="900"],[font-weight="bold"]) { font-weight: 500 !important; }',
    S + ' :is(main, aside, header, nav), ' + S + ' :is(main, aside, header, nav) * { letter-spacing: normal !important; }',
    S + ' main h1 { letter-spacing: -0.02em !important; }',
    S + ' main { line-height: 1.5; }',
]
with open("app/typescale.css", "w") as f:
    f.write("\n".join(css) + "\n")
print(f"app/typescale.css: {len(sizes)} sizes snapped")
